Repository todo-team-05/todo-max, pull requests merged in 2023-07, with the labels that each got.

#2 [FE] #1 build: 개발 환경 세팅
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md.md
  .gitignore
  FE/.eslintrc.cjs
  FE/.prettierrc
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/main.tsx
  FE/src/vite-env.d.ts
  FE/tsconfig.json
  FE/tsconfig.node.json
  FE/vite.config.ts
Labels: FE

#6 [FE] #1 style: 기본 스타일 요소 세팅
  FE/.gitignore
  FE/public/icons/close.svg
  FE/public/icons/edit.svg
  FE/public/icons/history.svg
  FE/public/icons/plus.svg
  FE/src/constants/colors.ts
  FE/src/styles/main.css
  FE/src/styles/theme.ts
Labels: FE, 🎨 style

#7 [FE] #1 style: emotion 의존성 설정
  FE/package-lock.json
  FE/package.json
  FE/src/components/Txt.tsx
  FE/src/constants/colors.ts
  FE/src/constants/fonts.ts
Labels: FE, 💄 design

#8 [FE] #3 feat: 메인페이지 배경 UI 구현
  FE/src/App.tsx
  FE/src/main.tsx
  FE/src/pages/MainPage.tsx
  FE/src/styles/main.css
  FE/src/styles/theme.ts
  FE/tsconfig.json
  FE/vite.config.ts
Labels: FE, ✨ feat

#11 [FE] #4 feat: 칼럼 영역 UI 구현
  FE/src/components/Button/PlusButton.tsx
  FE/src/components/ColumnList/Badge.tsx
  FE/src/components/ColumnList/ColumnList.tsx
  FE/src/components/ColumnList/ColumnTitle.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/components/header/Header.tsx
  FE/src/pages/MainPage.tsx
Labels: FE, ✨ feat

#12 [FE] feat #5: Alert 컴포넌트 구현
  FE/src/components/Alert/Alert.tsx
Labels: FE, Sprint#1, ✨ feat

#13 [FE] feat #5: 히스토리 레이어 UI 구현
  FE/public/icons/profileImg.png
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/components/History/HistoryIcon.tsx
  FE/src/components/History/HistoryItem.tsx
  FE/src/components/History/HistoryLayer.tsx
  FE/src/components/Txt.tsx
  FE/src/components/header/Header.tsx
  FE/src/constants/colors.ts
  FE/src/pages/MainPage.tsx
Labels: FE, ✨ feat, 💄 design

#23 [BE] build: DB 환경 조성
  be/docker-compose.yml
  be/src/main/resources/application-db.yml
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, Sprint#1, 🔧 build

#25 [BE] build: DB 환경 조성
  be/docker-compose.yml
  be/src/main/resources/application-db.yml
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, Sprint#1, 🔧 build

#26 [FE] build: Mock Server 구축, 패키지 수정, eslint 삭제
  FE/.eslintrc.cjs
  FE/package-lock.json
  FE/package.json
  FE/src/services/history.json
  FE/src/services/index.json
  FE/src/services/server.mjs
Labels: FE, 🔧 build

#27 [FE] #3: 히스토리 레이어 노출 및 애니메이션 효과
  FE/src/components/Button/CloseButton.tsx
  FE/src/components/History/HistoryIcon.tsx
  FE/src/components/History/HistoryItem.tsx
  FE/src/components/History/HistoryLayer.tsx
  FE/src/components/History/HistoryLayerFooter.tsx
  FE/src/components/History/NoHistory.tsx
  FE/src/components/header/Header.tsx
Labels: FE, ✨ feat

#28 [FE] feat #4: 칼럼 영역 Mock Data 사용해서 UI 구현
  FE/src/components/Card/Card.tsx
  FE/src/components/ColumnList/Badge.tsx
  FE/src/components/ColumnList/ColumnList.tsx
  FE/src/components/ColumnList/ColumnTitle.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/components/Txt.tsx
  FE/src/pages/MainPage.tsx
Labels: FE

#30 [FE] feat #29: MSW mock server 구현
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/main.tsx
  FE/src/mocks/Apis.ts
  FE/src/mocks/browers.ts
  FE/src/mocks/history.json
  FE/src/mocks/index.json
Labels: FE, Sprint#1, LOW, ✨ feat

#32 [FE] 버튼 컴포넌트 리팩토링 및 적용
  FE/src/components/Alert/Alert.tsx
  FE/src/components/Button/Button.tsx
  FE/src/components/Button/CloseButton.tsx
  FE/src/components/Button/CloseIcon.tsx
  FE/src/components/Button/EditButton.tsx
  FE/src/components/Button/EditIcon.tsx
  FE/src/components/Button/HistoryIcon.tsx
  FE/src/components/Button/IconButton.tsx
  FE/src/components/Button/PlusButton.tsx
  FE/src/components/Button/PlusIcon.tsx
  FE/src/components/Card/Card.tsx
  FE/src/components/ColumnList/ColumnTitle.tsx
  FE/src/components/History/HistoryLayer.tsx
Labels: FE, Sprint#1, LOW, ♻️ refactor

#33 [FE] Alert 컴포넌트 리팩토링
  FE/src/components/Alert/Alert.tsx
Labels: FE, Sprint#1, LOW, ♻️ refactor

#34 [FE] feat #5: 히스토리 닫기 애니메이션 및 기록 전체 삭제 구현
  FE/src/App.tsx
  FE/src/components/Alert/Alert.tsx
  FE/src/components/Button/Button.tsx
  FE/src/components/ColumnList/ColumnList.tsx
  FE/src/components/Dim/Dim.tsx
  FE/src/components/History/HistoryLayer.tsx
  FE/src/components/History/HistoryLayerFooter.tsx
  FE/src/components/header/Header.tsx
  FE/src/contexts/ModalContext.tsx
  FE/src/pages/MainPage.tsx
Labels: FE, ✨ feat

#35 [BE] feat: 카드 생성 기능 구현
  be/src/main/java/team5/todo/card/repository/CardRepository.java
  be/src/main/java/team5/todo/controller/CardController.java
  be/src/main/java/team5/todo/controller/dto/CardResponse.java
  be/src/main/java/team5/todo/controller/dto/CardSaveRequest.java
  be/src/main/java/team5/todo/controller/dto/CategoryResponse.java
  be/src/main/java/team5/todo/domain/Card.java
  be/src/main/java/team5/todo/domain/Category.java
  be/src/main/java/team5/todo/repository/CardRepository.java
  be/src/main/java/team5/todo/repository/CategoryRepository.java
  be/src/main/java/team5/todo/service/CardService.java
  be/src/main/java/team5/todo/service/CategoryService.java
  be/src/test/java/team5/todo/repository/CardRepositoryTest.java
  be/src/test/java/team5/todo/repository/CategoryRepositoryTest.java
Labels: BE, Sprint#1, ✨ feat

#39 [FE] feat #38: 카드 등록 컴포넌트 및 기능 구현
  FE/src/components/Button/Button.tsx
  FE/src/components/Button/IconButton.tsx
  FE/src/components/Card/AddCard.tsx
  FE/src/components/ColumnList/ColumnTitle.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/constants/opacity.ts
Labels: FE, Sprint#1, HIGH, ✨ feat

#42 [FE] feat: 카드 삭제 기능
  FE/src/components/Alert/Alert.tsx
  FE/src/components/Card/AddCard.tsx
  FE/src/components/Card/DefaultCard.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/components/History/HistoryLayer.tsx
  FE/src/components/History/HistoryLayerFooter.tsx
  FE/src/components/header/Header.tsx
  FE/src/constants/shadow.ts
  FE/src/contexts/ModalContext.tsx
  FE/src/pages/MainPage.tsx
  FE/src/utils/getUserDevice.ts
Labels: FE, Sprint#1, HIGH, ✨ feat

#45 [FE] feat #44: 카드 수정 기능 추가
  FE/src/components/Card/DefaultCard.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
Labels: FE, Sprint#2, HIGH, ✨ feat

#49 [BE] history 기능 구현
  be/src/main/java/team5/todo/controller/CardController.java
  be/src/main/java/team5/todo/controller/HistoryController.java
  be/src/main/java/team5/todo/controller/dto/HistoryResponse.java
  be/src/main/java/team5/todo/domain/Action.java
  be/src/main/java/team5/todo/domain/History.java
  be/src/main/java/team5/todo/repository/CardRepository.java
  be/src/main/java/team5/todo/repository/CategoryRepository.java
  be/src/main/java/team5/todo/repository/HistoryRepository.java
  be/src/main/java/team5/todo/service/CardService.java
  be/src/main/java/team5/todo/service/CategoryService.java
  be/src/main/java/team5/todo/service/HistoryService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/team5/todo/controller/CardControllerTest.java
  be/src/test/java/team5/todo/controller/HistoryControllerTest.java
  be/src/test/java/team5/todo/repository/CardRepositoryTest.java
  be/src/test/java/team5/todo/repository/HistoryRepositoryTest.java
  be/src/test/java/team5/todo/service/HistoryServiceTest.java
  be/src/test/resources/schema/data.sql
  be/src/test/resources/schema/schema.sql
Labels: BE, Sprint#2, ✨ feat

#50 [FE] feat #47: 칼럼 추가, 변경, 삭제 기능 추가
  FE/src/App.tsx
  FE/src/components/Alert/Alert.tsx
  FE/src/components/Button/Button.tsx
  FE/src/components/Button/IconButton.tsx
  FE/src/components/Card/AddCard.tsx
  FE/src/components/Card/DefaultCard.tsx
  FE/src/components/ColumnList/Badge.tsx
  FE/src/components/ColumnList/ColumnList.tsx
  FE/src/components/ColumnList/ColumnTitle.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/components/Dim/Dim.tsx
  FE/src/components/History/HistoryIcon.tsx
  FE/src/components/History/HistoryItem.tsx
  FE/src/components/History/HistoryLayer.tsx
  FE/src/components/History/HistoryLayerFooter.tsx
  FE/src/components/History/NoHistory.tsx
  FE/src/components/header/Header.tsx
  FE/src/contexts/HistoryContext.tsx
  FE/src/contexts/ModalContext.tsx
  FE/src/mocks/history.json
  FE/src/mocks/index.json
  FE/src/pages/MainPage.tsx
  FE/src/services/history.json
  FE/src/services/index.json
  FE/src/utils/getUserDevice.ts
Labels: FE, Sprint#2, HIGH, ✨ feat

#52 [FE] feat: 카드 이동 및 수정 기능
  FE/src/App.tsx
  FE/src/components/Alert/Alert.tsx
  FE/src/components/Card/CloneCard.tsx
  FE/src/components/Card/DefaultCard.tsx
  FE/src/components/ColumnList/ColumnWrapper.tsx
  FE/src/components/Dim/Dim.tsx
  FE/src/contexts/CardContext.tsx
  FE/src/mocks/Apis.ts
  FE/src/mocks/index.json
  FE/src/pages/MainPage.tsx
  FE/vite.config.ts
Labels: FE, ✨ feat

#54 [BE] Integration 테스트 작성
  be/src/main/java/team5/todo/controller/CardController.java
  be/src/test/java/team5/todo/annotation/IntegrationTest.java
  be/src/test/java/team5/todo/fixture/FixtureFactory.java
  be/src/test/java/team5/todo/integration/CardIntegrationTest.java
  be/src/test/java/team5/todo/integration/HistoryIntegrationTest.java
  be/src/test/java/team5/todo/integration/Integration.java
  be/src/test/resources/schema/data.sql
Labels: BE, Sprint#1, ✅ test

#56 [BE] 예외 처리, 통합 테스트 작성
  be/build.gradle
  be/src/main/java/team5/todo/config/GlobalExceptionHandler.java
  be/src/main/java/team5/todo/controller/CardController.java
  be/src/main/java/team5/todo/controller/dto/CardModifyRequest.java
  be/src/main/java/team5/todo/controller/dto/CardMoveRequest.java
  be/src/main/java/team5/todo/controller/dto/CardSaveRequest.java
  be/src/main/java/team5/todo/exception/ErrorResponse.java
  be/src/main/java/team5/todo/repository/HistoryRepository.java
  be/src/test/java/team5/todo/annotation/IntegrationTest.java
  be/src/test/java/team5/todo/controller/CardControllerTest.java
  be/src/test/java/team5/todo/integration/CategoryIntegrationTest.java
  be/src/test/java/team5/todo/integration/HistoryIntegrationTest.java
Labels: BE, Sprint#2, ✨ feat, 🐛 fix, ✅ test
